# #!/bin/sh


service mysql start
if [ ! -e /var/lib/mysql/$MYSQL_DATABASE ]; then
	mysql -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE" -p$MYSQL_PASSWORD
	mysql -e "CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'" -p$MYSQL_PASSWORD
	mysql -e "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%'; FLUSH PRIVILEGES;" -p$MYSQL_PASSWORD
	mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD'; FLUSH PRIVILEGES;" -p$MYSQL_PASSWORD
fi
mysqladmin -u$MYSQL_ROOT -p$MYSQL_ROOT_PASSWORD shutdown
exec mysqld_safe